[EV, scriptFolder, projectRoot] = Initialize_Project();
%%=========================================================================
% Load Vehicle Calculation Results
%==========================================================================

loadedVehicle = load( ...
    fullfile(projectRoot,'Data','Vehicle_Calculations.mat'), ...
    'EV');

EV.Calculated = loadedVehicle.EV.Calculated;
%%=========================================================================
% Time Vector
% Generates the simulation time vector.
%==========================================================================

EV.DriveCycle.Time = ...
    (0:1:120)';

TimeStep = ...
    EV.DriveCycle.Time(2) - EV.DriveCycle.Time(1);

%%=========================================================================
% Vehicle Speed Profile
% Generates a simple urban drive cycle.
%==========================================================================

EV.DriveCycle.Speedkmh = ...
    zeros(size(EV.DriveCycle.Time));
EV.DriveCycle.Speedkmh(1:21) = ...
    linspace(0,50,21);
EV.DriveCycle.Speedkmh(22:61) = ...
    50;
EV.DriveCycle.Speedkmh(62:81) = ...
    linspace(50,20,20);
EV.DriveCycle.Speedkmh(82:101) = ...
    linspace(20,0,20);
EV.DriveCycle.Speedkmh(102:end) = ...
    0;
%%=========================================================================
% Speed Conversion
% Converts vehicle speed to SI units.
%==========================================================================

EV.DriveCycle.Speed = ...
    EV.DriveCycle.Speedkmh / 3.6;
%%=========================================================================
% Vehicle Acceleration
% Calculates acceleration from the speed profile.
%==========================================================================
EV.DriveCycle.Acceleration = ...
    [0;
    diff(EV.DriveCycle.Speed) / TimeStep];

%%=========================================================================
% Distance Calculation
% Calculates cumulative distance travelled.
%==========================================================================
EV.DriveCycle.Distancem = ...
    cumsum(EV.DriveCycle.Speed * TimeStep);

%%=========================================================================
% Tractive Force
% Calculates the required tractive force during the drive cycle.
%==========================================================================

EV.DriveCycle.Calculated.TractiveForceN = ...
    EV.Vehicle.Mass .* EV.DriveCycle.Acceleration + ...
    EV.Calculated.RollingResistanceForce + ...
    EV.Calculated.AerodynamicDragForce;
%%=========================================================================
% Wheel Power
% Calculates wheel power during the drive cycle.
%==========================================================================

EV.DriveCycle.Calculated.WheelPowerkW = ...
    (EV.DriveCycle.Calculated.TractiveForceN .* ...
    EV.DriveCycle.Speed) / ...
    1000;
%%=========================================================================
% Motor Power
% Calculates required motor power.
%==========================================================================

EV.DriveCycle.Calculated.MotorPowerkW = ...
    EV.DriveCycle.Calculated.WheelPowerkW / ...
    EV.Transmission.Efficiency;
%%=========================================================================
% Battery Power
% Calculates battery power demand.
%==========================================================================

EV.DriveCycle.Calculated.BatteryPowerkW = ...
    EV.DriveCycle.Calculated.MotorPowerkW / ...
    EV.Inverter.Efficiency;
%%=========================================================================
% Energy Consumption
% Calculates cumulative battery energy consumption.
%==========================================================================

EnergyPerSecond = ...
    EV.DriveCycle.Calculated.BatteryPowerkW / ...
    3600;

EV.DriveCycle.Calculated.EnergykWh = ...
    cumsum(EnergyPerSecond);
%%=========================================================================
% Trip Statistics
%==========================================================================

DistancePerStepkm = ...
    EV.DriveCycle.Speedkmh .* ...
    TimeStep / 3600;

EV.DriveCycle.Calculated.Distancekm = ...
    sum(DistancePerStepkm);
EV.DriveCycle.Calculated.AverageSpeedkmh = ...
    mean(EV.DriveCycle.Speedkmh);
EV.DriveCycle.Calculated.MaximumSpeedkmh = ...
    max(EV.DriveCycle.Speedkmh);
EV.DriveCycle.Calculated.TripTimeSeconds = ...
    EV.DriveCycle.Time(end);
if EV.DriveCycle.Calculated.Distancekm > 0
    EV.DriveCycle.Calculated.EnergyConsumptionkWhPerkm = ...
        EV.DriveCycle.Calculated.EnergykWh(end) / ...
        EV.DriveCycle.Calculated.Distancekm;
else
    EV.DriveCycle.Calculated.EnergyConsumptionkWhPerkm = 0;
end

%%=========================================================================
% Drive Cycle Report
%==========================================================================

fprintf('\n');
fprintf('============================================================\n');
fprintf('              SMART EV POWERTRAIN SIMULATOR\n');
fprintf('                  DRIVE CYCLE REPORT\n');
fprintf('============================================================\n\n');

fprintf('Drive Cycle\n');
fprintf('------------------------------------------------------------\n');

fprintf('Simulation Time      : %.0f s\n', ...
    EV.DriveCycle.Calculated.TripTimeSeconds);

fprintf('Average Speed        : %.2f km/h\n', ...
    EV.DriveCycle.Calculated.AverageSpeedkmh);

fprintf('Maximum Speed        : %.2f km/h\n\n', ...
    EV.DriveCycle.Calculated.MaximumSpeedkmh);

fprintf('Trip Statistics\n');
fprintf('------------------------------------------------------------\n');

fprintf('Distance Travelled   : %.3f km\n', ...
    EV.DriveCycle.Calculated.Distancekm);

fprintf('Energy Consumed      : %.4f kWh\n', ...
    EV.DriveCycle.Calculated.EnergykWh(end));

fprintf('Energy Consumption   : %.4f kWh/km\n\n', ...
    EV.DriveCycle.Calculated.EnergyConsumptionkWhPerkm);

fprintf('Power Requirements\n');
fprintf('------------------------------------------------------------\n');

fprintf('Peak Wheel Power     : %.2f kW\n', ...
    max(EV.DriveCycle.Calculated.WheelPowerkW));

fprintf('Peak Motor Power     : %.2f kW\n', ...
    max(EV.DriveCycle.Calculated.MotorPowerkW));

fprintf('Peak Battery Power   : %.2f kW\n\n', ...
    max(EV.DriveCycle.Calculated.BatteryPowerkW));

fprintf('Validation\n');
fprintf('------------------------------------------------------------\n');

fprintf('Overall Status       : PASS\n');

fprintf('\n============================================================\n');

%%=========================================================================
% Plot 1
% Vehicle Speed vs Time
%==========================================================================

figSpeed = figure( ...
    'Name','Vehicle Speed Profile', ...
    'Color','w');

plot( ...
    EV.DriveCycle.Time, ...
    EV.DriveCycle.Speedkmh, ...
    'LineWidth',2);

grid on

box on

xlabel( ...
    'Time (s)', ...
    'FontSize',11);

ylabel( ...
    'Speed (km/h)', ...
    'FontSize',11);

title( ...
    'Vehicle Speed Profile', ...
    'FontWeight','bold');

set(gca, ...
    'FontSize',11, ...
    'LineWidth',1.2);

%%=========================================================================
% Plot 2
% Vehicle Acceleration vs Time
%==========================================================================

figAcceleration = figure( ...
    'Name','Vehicle Acceleration', ...
    'Color','w');

plot( ...
    EV.DriveCycle.Time, ...
    EV.DriveCycle.Acceleration, ...
    'LineWidth',2);

grid on

box on

xlabel( ...
    'Time (s)', ...
    'FontSize',11);

ylabel( ...
    'Acceleration (m/s^2)', ...
    'FontSize',11);

title( ...
    'Vehicle Acceleration', ...
    'FontWeight','bold');

set(gca, ...
    'FontSize',11, ...
    'LineWidth',1.2);

%%=========================================================================
% Plot 3
% Tractive Force vs Time
%==========================================================================

figTractiveForce = figure( ...
    'Name','Required Tractive Force', ...
    'Color','w');

plot( ...
    EV.DriveCycle.Time, ...
    EV.DriveCycle.Calculated.TractiveForceN, ...
    'LineWidth',2);

grid on

box on

xlabel( ...
    'Time (s)', ...
    'FontSize',11);

ylabel( ...
    'Force (N)', ...
    'FontSize',11);

title( ...
    'Required Tractive Force', ...
    'FontWeight','bold');

set(gca, ...
    'FontSize',11, ...
    'LineWidth',1.2);

%%=========================================================================
% Plot 4
% Battery Power vs Time
%==========================================================================

figBatteryPower = figure( ...
    'Name','Battery Power Demand', ...
    'Color','w');

plot( ...
    EV.DriveCycle.Time, ...
    EV.DriveCycle.Calculated.BatteryPowerkW, ...
    'LineWidth',2);

grid on

box on

xlabel( ...
    'Time (s)', ...
    'FontSize',11);

ylabel( ...
    'Power (kW)', ...
    'FontSize',11);

title( ...
    'Battery Power Demand', ...
    'FontWeight','bold');

set(gca, ...
    'FontSize',11, ...
    'LineWidth',1.2);

%%=========================================================================
% Plot 5
% Energy Consumption vs Time
%==========================================================================

figEnergy = figure( ...
    'Name','Cumulative Energy Consumption', ...
    'Color','w');

plot( ...
    EV.DriveCycle.Time, ...
    EV.DriveCycle.Calculated.EnergykWh, ...
    'LineWidth',2);

grid on

box on

xlabel( ...
    'Time (s)', ...
    'FontSize',11);

ylabel( ...
    'Energy (kWh)', ...
    'FontSize',11);

title( ...
    'Cumulative Energy Consumption', ...
    'FontWeight','bold');

set(gca, ...
    'FontSize',11, ...
    'LineWidth',1.2);

%%=========================================================================
% Save Figures
% Saves all generated plots.
%==========================================================================

resultsFolder = fullfile(projectRoot,'Results','DriveCycle');

if ~exist(resultsFolder,'dir')
    mkdir(resultsFolder);
end

exportgraphics( ...
    figSpeed, ...
    fullfile(resultsFolder,'Speed.png'), ...
    'Resolution',300);

exportgraphics( ...
    figAcceleration, ...
    fullfile(resultsFolder,'Acceleration.png'), ...
    'Resolution',300);

exportgraphics( ...
    figTractiveForce, ...
    fullfile(resultsFolder,'TractiveForce.png'), ...
    'Resolution',300);

exportgraphics( ...
    figBatteryPower, ...
    fullfile(resultsFolder,'BatteryPower.png'), ...
    'Resolution',300);

exportgraphics( ...
    figEnergy, ...
    fullfile(resultsFolder,'Energy.png'), ...
    'Resolution',300);
%%=========================================================================
% Close Figures
%==========================================================================

close(figSpeed);

close(figAcceleration);

close(figTractiveForce);

close(figBatteryPower);

close(figEnergy);
%%=========================================================================
% Save Results
% Saves drive cycle calculation results.
%==========================================================================

save( ...
    fullfile(projectRoot,'Data','Drive_Cycle.mat'), ...
    'EV');

fprintf('\nResults saved successfully.\n');

fprintf('Location : %s\n', ...
    fullfile(projectRoot,'Data','Drive_Cycle.mat'));
